spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identify_service"
    password: 1234
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identify